springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Service Desk
        url: /aggregate/service-desk/v3/api-docs
      - name: User Service
        url: /aggregate/user-service/v3/api-docs
  api-docs:
    path: /api-docs